title: The test blog
author: GBox
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a very poorly created SEO centered title.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
